default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--config, b3/.flake8]
  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v1.0.0
    hooks:
      - id: encryption-check
